//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ndShapeCapsule : ndShapeConvex {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ndShapeCapsule(global::System.IntPtr cPtr, bool cMemoryOwn) : base(newtonPINVOKE.ndShapeCapsule_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ndShapeCapsule obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          newtonPINVOKE.delete_ndShapeCapsule(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ndShapeCapsule(SWIGTYPE_p_ndLoadSaveBase__ndLoadDescriptor desc) : this(newtonPINVOKE.new_ndShapeCapsule__SWIG_0(SWIGTYPE_p_ndLoadSaveBase__ndLoadDescriptor.getCPtr(desc)), true) {
    if (newtonPINVOKE.SWIGPendingException.Pending) throw newtonPINVOKE.SWIGPendingException.Retrieve();
  }

  public ndShapeCapsule(SWIGTYPE_p_ndFloat32 radio0, SWIGTYPE_p_ndFloat32 radio1, SWIGTYPE_p_ndFloat32 height) : this(newtonPINVOKE.new_ndShapeCapsule__SWIG_1(SWIGTYPE_p_ndFloat32.getCPtr(radio0), SWIGTYPE_p_ndFloat32.getCPtr(radio1), SWIGTYPE_p_ndFloat32.getCPtr(height)), true) {
    if (newtonPINVOKE.SWIGPendingException.Pending) throw newtonPINVOKE.SWIGPendingException.Retrieve();
  }

  public override ndShapeCapsule GetAsShapeCapsule() {
    global::System.IntPtr cPtr = newtonPINVOKE.ndShapeCapsule_GetAsShapeCapsule(swigCPtr);
    ndShapeCapsule ret = (cPtr == global::System.IntPtr.Zero) ? null : new ndShapeCapsule(cPtr, false);
    return ret;
  }

}
