//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ndShapeSphere : ndShapeConvex {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ndShapeSphere(global::System.IntPtr cPtr, bool cMemoryOwn) : base(newtonPINVOKE.ndShapeSphere_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ndShapeSphere obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          newtonPINVOKE.delete_ndShapeSphere(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ndShapeSphere(SWIGTYPE_p_ndFloat32 radius) : this(newtonPINVOKE.new_ndShapeSphere__SWIG_0(SWIGTYPE_p_ndFloat32.getCPtr(radius)), true) {
    if (newtonPINVOKE.SWIGPendingException.Pending) throw newtonPINVOKE.SWIGPendingException.Retrieve();
  }

  public ndShapeSphere(SWIGTYPE_p_ndLoadSaveBase__ndLoadDescriptor desc) : this(newtonPINVOKE.new_ndShapeSphere__SWIG_1(SWIGTYPE_p_ndLoadSaveBase__ndLoadDescriptor.getCPtr(desc)), true) {
    if (newtonPINVOKE.SWIGPendingException.Pending) throw newtonPINVOKE.SWIGPendingException.Retrieve();
  }

  public override ndShapeSphere GetAsShapeSphere() {
    global::System.IntPtr cPtr = newtonPINVOKE.ndShapeSphere_GetAsShapeSphere(swigCPtr);
    ndShapeSphere ret = (cPtr == global::System.IntPtr.Zero) ? null : new ndShapeSphere(cPtr, false);
    return ret;
  }

}
