//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ndShapeChamferCylinder : ndShapeConvex {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ndShapeChamferCylinder(global::System.IntPtr cPtr, bool cMemoryOwn) : base(newtonPINVOKE.ndShapeChamferCylinder_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ndShapeChamferCylinder obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          newtonPINVOKE.delete_ndShapeChamferCylinder(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ndShapeChamferCylinder(SWIGTYPE_p_ndFloat32 radius, SWIGTYPE_p_ndFloat32 height) : this(newtonPINVOKE.new_ndShapeChamferCylinder__SWIG_0(SWIGTYPE_p_ndFloat32.getCPtr(radius), SWIGTYPE_p_ndFloat32.getCPtr(height)), true) {
    if (newtonPINVOKE.SWIGPendingException.Pending) throw newtonPINVOKE.SWIGPendingException.Retrieve();
  }

  public ndShapeChamferCylinder(SWIGTYPE_p_ndLoadSaveBase__ndLoadDescriptor desc) : this(newtonPINVOKE.new_ndShapeChamferCylinder__SWIG_1(SWIGTYPE_p_ndLoadSaveBase__ndLoadDescriptor.getCPtr(desc)), true) {
    if (newtonPINVOKE.SWIGPendingException.Pending) throw newtonPINVOKE.SWIGPendingException.Retrieve();
  }

  public override ndShapeChamferCylinder GetAsShapeChamferCylinder() {
    global::System.IntPtr cPtr = newtonPINVOKE.ndShapeChamferCylinder_GetAsShapeChamferCylinder(swigCPtr);
    ndShapeChamferCylinder ret = (cPtr == global::System.IntPtr.Zero) ? null : new ndShapeChamferCylinder(cPtr, false);
    return ret;
  }

}
