//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ndShapeID {
  m_box = 0,
  m_cone,
  m_sphere,
  m_capsule,
  m_cylinder,
  m_chamferCylinder,
  m_convexHull,
  m_compound,
  m_staticMesh,
  m_heightField,
  m_staticProceduralMesh,
  m_nullCollision,
  m_pointCollision,
  m_polygonCollision,
  m_boundingBoxHierachy
}
