/*
Copyright 2018 Ioannis Makris

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// This file was generated by glatter.py script.




typedef union glatter_extension_support_status_union_GLX
{
    int inexed_extensions[67];
    struct {
        int has_GLX_3DFX_multisample;
        int has_GLX_AMD_gpu_association;
        int has_GLX_ARB_context_flush_control;
        int has_GLX_ARB_create_context;
        int has_GLX_ARB_create_context_no_error;
        int has_GLX_ARB_create_context_profile;
        int has_GLX_ARB_create_context_robustness;
        int has_GLX_ARB_fbconfig_float;
        int has_GLX_ARB_framebuffer_sRGB;
        int has_GLX_ARB_get_proc_address;
        int has_GLX_ARB_multisample;
        int has_GLX_ARB_render_texture;
        int has_GLX_ARB_robustness_application_isolation;
        int has_GLX_ARB_robustness_share_group_isolation;
        int has_GLX_ARB_vertex_buffer_object;
        int has_GLX_EXT_buffer_age;
        int has_GLX_EXT_create_context_es2_profile;
        int has_GLX_EXT_create_context_es_profile;
        int has_GLX_EXT_fbconfig_packed_float;
        int has_GLX_EXT_framebuffer_sRGB;
        int has_GLX_EXT_import_context;
        int has_GLX_EXT_libglvnd;
        int has_GLX_EXT_no_config_context;
        int has_GLX_EXT_stereo_tree;
        int has_GLX_EXT_swap_control;
        int has_GLX_EXT_swap_control_tear;
        int has_GLX_EXT_texture_from_pixmap;
        int has_GLX_EXT_visual_info;
        int has_GLX_EXT_visual_rating;
        int has_GLX_INTEL_swap_event;
        int has_GLX_MESA_agp_offset;
        int has_GLX_MESA_copy_sub_buffer;
        int has_GLX_MESA_pixmap_colormap;
        int has_GLX_MESA_query_renderer;
        int has_GLX_MESA_release_buffers;
        int has_GLX_MESA_set_3dfx_mode;
        int has_GLX_MESA_swap_control;
        int has_GLX_MESA_swap_frame_usage;
        int has_GLX_NV_copy_buffer;
        int has_GLX_NV_copy_image;
        int has_GLX_NV_delay_before_swap;
        int has_GLX_NV_float_buffer;
        int has_GLX_NV_multisample_coverage;
        int has_GLX_NV_present_video;
        int has_GLX_NV_robustness_video_memory_purge;
        int has_GLX_NV_swap_group;
        int has_GLX_NV_video_capture;
        int has_GLX_NV_video_out;
        int has_GLX_OML_swap_method;
        int has_GLX_OML_sync_control;
        int has_GLX_SGIS_blended_overlay;
        int has_GLX_SGIS_multisample;
        int has_GLX_SGIS_shared_multisample;
        int has_GLX_SGIX_dmbuffer;
        int has_GLX_SGIX_fbconfig;
        int has_GLX_SGIX_hyperpipe;
        int has_GLX_SGIX_pbuffer;
        int has_GLX_SGIX_swap_barrier;
        int has_GLX_SGIX_swap_group;
        int has_GLX_SGIX_video_resize;
        int has_GLX_SGIX_video_source;
        int has_GLX_SGIX_visual_select_group;
        int has_GLX_SGI_cushion;
        int has_GLX_SGI_make_current_read;
        int has_GLX_SGI_swap_control;
        int has_GLX_SGI_video_sync;
        int has_GLX_SUN_get_transparent_index;
    };
} glatter_extension_support_status_GLX_t;


#define glatter_GLX_3DFX_multisample glatter_get_extension_support_GLX().has_GLX_3DFX_multisample
#define glatter_GLX_AMD_gpu_association glatter_get_extension_support_GLX().has_GLX_AMD_gpu_association
#define glatter_GLX_ARB_context_flush_control glatter_get_extension_support_GLX().has_GLX_ARB_context_flush_control
#define glatter_GLX_ARB_create_context glatter_get_extension_support_GLX().has_GLX_ARB_create_context
#define glatter_GLX_ARB_create_context_no_error glatter_get_extension_support_GLX().has_GLX_ARB_create_context_no_error
#define glatter_GLX_ARB_create_context_profile glatter_get_extension_support_GLX().has_GLX_ARB_create_context_profile
#define glatter_GLX_ARB_create_context_robustness glatter_get_extension_support_GLX().has_GLX_ARB_create_context_robustness
#define glatter_GLX_ARB_fbconfig_float glatter_get_extension_support_GLX().has_GLX_ARB_fbconfig_float
#define glatter_GLX_ARB_framebuffer_sRGB glatter_get_extension_support_GLX().has_GLX_ARB_framebuffer_sRGB
#define glatter_GLX_ARB_get_proc_address glatter_get_extension_support_GLX().has_GLX_ARB_get_proc_address
#define glatter_GLX_ARB_multisample glatter_get_extension_support_GLX().has_GLX_ARB_multisample
#define glatter_GLX_ARB_render_texture glatter_get_extension_support_GLX().has_GLX_ARB_render_texture
#define glatter_GLX_ARB_robustness_application_isolation glatter_get_extension_support_GLX().has_GLX_ARB_robustness_application_isolation
#define glatter_GLX_ARB_robustness_share_group_isolation glatter_get_extension_support_GLX().has_GLX_ARB_robustness_share_group_isolation
#define glatter_GLX_ARB_vertex_buffer_object glatter_get_extension_support_GLX().has_GLX_ARB_vertex_buffer_object
#define glatter_GLX_EXT_buffer_age glatter_get_extension_support_GLX().has_GLX_EXT_buffer_age
#define glatter_GLX_EXT_create_context_es2_profile glatter_get_extension_support_GLX().has_GLX_EXT_create_context_es2_profile
#define glatter_GLX_EXT_create_context_es_profile glatter_get_extension_support_GLX().has_GLX_EXT_create_context_es_profile
#define glatter_GLX_EXT_fbconfig_packed_float glatter_get_extension_support_GLX().has_GLX_EXT_fbconfig_packed_float
#define glatter_GLX_EXT_framebuffer_sRGB glatter_get_extension_support_GLX().has_GLX_EXT_framebuffer_sRGB
#define glatter_GLX_EXT_import_context glatter_get_extension_support_GLX().has_GLX_EXT_import_context
#define glatter_GLX_EXT_libglvnd glatter_get_extension_support_GLX().has_GLX_EXT_libglvnd
#define glatter_GLX_EXT_no_config_context glatter_get_extension_support_GLX().has_GLX_EXT_no_config_context
#define glatter_GLX_EXT_stereo_tree glatter_get_extension_support_GLX().has_GLX_EXT_stereo_tree
#define glatter_GLX_EXT_swap_control glatter_get_extension_support_GLX().has_GLX_EXT_swap_control
#define glatter_GLX_EXT_swap_control_tear glatter_get_extension_support_GLX().has_GLX_EXT_swap_control_tear
#define glatter_GLX_EXT_texture_from_pixmap glatter_get_extension_support_GLX().has_GLX_EXT_texture_from_pixmap
#define glatter_GLX_EXT_visual_info glatter_get_extension_support_GLX().has_GLX_EXT_visual_info
#define glatter_GLX_EXT_visual_rating glatter_get_extension_support_GLX().has_GLX_EXT_visual_rating
#define glatter_GLX_INTEL_swap_event glatter_get_extension_support_GLX().has_GLX_INTEL_swap_event
#define glatter_GLX_MESA_agp_offset glatter_get_extension_support_GLX().has_GLX_MESA_agp_offset
#define glatter_GLX_MESA_copy_sub_buffer glatter_get_extension_support_GLX().has_GLX_MESA_copy_sub_buffer
#define glatter_GLX_MESA_pixmap_colormap glatter_get_extension_support_GLX().has_GLX_MESA_pixmap_colormap
#define glatter_GLX_MESA_query_renderer glatter_get_extension_support_GLX().has_GLX_MESA_query_renderer
#define glatter_GLX_MESA_release_buffers glatter_get_extension_support_GLX().has_GLX_MESA_release_buffers
#define glatter_GLX_MESA_set_3dfx_mode glatter_get_extension_support_GLX().has_GLX_MESA_set_3dfx_mode
#define glatter_GLX_MESA_swap_control glatter_get_extension_support_GLX().has_GLX_MESA_swap_control
#define glatter_GLX_MESA_swap_frame_usage glatter_get_extension_support_GLX().has_GLX_MESA_swap_frame_usage
#define glatter_GLX_NV_copy_buffer glatter_get_extension_support_GLX().has_GLX_NV_copy_buffer
#define glatter_GLX_NV_copy_image glatter_get_extension_support_GLX().has_GLX_NV_copy_image
#define glatter_GLX_NV_delay_before_swap glatter_get_extension_support_GLX().has_GLX_NV_delay_before_swap
#define glatter_GLX_NV_float_buffer glatter_get_extension_support_GLX().has_GLX_NV_float_buffer
#define glatter_GLX_NV_multisample_coverage glatter_get_extension_support_GLX().has_GLX_NV_multisample_coverage
#define glatter_GLX_NV_present_video glatter_get_extension_support_GLX().has_GLX_NV_present_video
#define glatter_GLX_NV_robustness_video_memory_purge glatter_get_extension_support_GLX().has_GLX_NV_robustness_video_memory_purge
#define glatter_GLX_NV_swap_group glatter_get_extension_support_GLX().has_GLX_NV_swap_group
#define glatter_GLX_NV_video_capture glatter_get_extension_support_GLX().has_GLX_NV_video_capture
#define glatter_GLX_NV_video_out glatter_get_extension_support_GLX().has_GLX_NV_video_out
#define glatter_GLX_OML_swap_method glatter_get_extension_support_GLX().has_GLX_OML_swap_method
#define glatter_GLX_OML_sync_control glatter_get_extension_support_GLX().has_GLX_OML_sync_control
#define glatter_GLX_SGIS_blended_overlay glatter_get_extension_support_GLX().has_GLX_SGIS_blended_overlay
#define glatter_GLX_SGIS_multisample glatter_get_extension_support_GLX().has_GLX_SGIS_multisample
#define glatter_GLX_SGIS_shared_multisample glatter_get_extension_support_GLX().has_GLX_SGIS_shared_multisample
#define glatter_GLX_SGIX_dmbuffer glatter_get_extension_support_GLX().has_GLX_SGIX_dmbuffer
#define glatter_GLX_SGIX_fbconfig glatter_get_extension_support_GLX().has_GLX_SGIX_fbconfig
#define glatter_GLX_SGIX_hyperpipe glatter_get_extension_support_GLX().has_GLX_SGIX_hyperpipe
#define glatter_GLX_SGIX_pbuffer glatter_get_extension_support_GLX().has_GLX_SGIX_pbuffer
#define glatter_GLX_SGIX_swap_barrier glatter_get_extension_support_GLX().has_GLX_SGIX_swap_barrier
#define glatter_GLX_SGIX_swap_group glatter_get_extension_support_GLX().has_GLX_SGIX_swap_group
#define glatter_GLX_SGIX_video_resize glatter_get_extension_support_GLX().has_GLX_SGIX_video_resize
#define glatter_GLX_SGIX_video_source glatter_get_extension_support_GLX().has_GLX_SGIX_video_source
#define glatter_GLX_SGIX_visual_select_group glatter_get_extension_support_GLX().has_GLX_SGIX_visual_select_group
#define glatter_GLX_SGI_cushion glatter_get_extension_support_GLX().has_GLX_SGI_cushion
#define glatter_GLX_SGI_make_current_read glatter_get_extension_support_GLX().has_GLX_SGI_make_current_read
#define glatter_GLX_SGI_swap_control glatter_get_extension_support_GLX().has_GLX_SGI_swap_control
#define glatter_GLX_SGI_video_sync glatter_get_extension_support_GLX().has_GLX_SGI_video_sync
#define glatter_GLX_SUN_get_transparent_index glatter_get_extension_support_GLX().has_GLX_SUN_get_transparent_index

