/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#ifndef SWIG_newton_WRAP_H_
#define SWIG_newton_WRAP_H_


#ifndef SWIGIMPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGDLLIMPORT
#   else
#     define SWIGDLLIMPORT __declspec(dllimport)
#   endif
# else
#   define SWIGDLLIMPORT
# endif
# define SWIGIMPORT extern SWIGDLLIMPORT
#endif

#include <stddef.h>


typedef struct SwigObj SwigObj;

typedef struct SwigObj_SWIG_CException SWIG_CException;

typedef struct SwigObj_NewtonWorld NewtonWorld;

#ifdef __cplusplus
extern "C" {
#endif

SWIGIMPORT SWIG_CException* SWIG_CException_copy(SWIG_CException* carg1);

SWIGIMPORT void SWIG_CException_delete(SWIG_CException* carg1);

SWIGIMPORT int SWIG_CException_code_get(SWIG_CException* carg1);

SWIGIMPORT char * SWIG_CException_msg_get(SWIG_CException* carg1);

SWIGIMPORT SWIG_CException* SWIG_CException_get_pending();

SWIGIMPORT void SWIG_CException_reset_pending();

SWIGIMPORT NewtonWorld* NewtonWorld_new();

SWIGIMPORT void NewtonWorld_delete(NewtonWorld* carg1);

SWIGIMPORT void NewtonWorld_Update(NewtonWorld* carg1, float carg2);

SWIGIMPORT void NewtonWorld_SetSubSteps(NewtonWorld* carg1, int carg2);

SWIGIMPORT void NewtonWorld_SetIterations(NewtonWorld* carg1, int carg2);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus

namespace newton {

class SWIG_CException;
class NewtonWorld;

class SWIG_CException {
public:
  SWIG_CException(SWIG_CException const & ex);
  ~SWIG_CException() {
    if (swig_owns_self_)
      SWIG_CException_delete(swig_self_);
  }
  int code() const;
  char * msg() const;
  static SWIG_CException * get_pending();
  static void reset_pending();

  explicit SWIG_CException(SwigObj_SWIG_CException* swig_self, bool swig_owns_self = true) noexcept : swig_self_{swig_self}, swig_owns_self_{swig_owns_self} {}
  SWIG_CException& operator=(SWIG_CException const&) = delete;
  SWIG_CException(SWIG_CException&& obj) noexcept : swig_self_{obj.swig_self_}, swig_owns_self_{obj.swig_owns_self_} { obj.swig_owns_self_ = false; }
  SWIG_CException& operator=(SWIG_CException&& obj) noexcept {
    if (swig_owns_self_)
      SWIG_CException_delete(swig_self_);
    swig_self_ = obj.swig_self_;
    swig_owns_self_ = obj.swig_owns_self_;
    obj.swig_owns_self_ = false;
    return *this;
  }
  SwigObj_SWIG_CException* swig_self() const noexcept { return swig_self_; }
  SwigObj_SWIG_CException* swig_self_;
  bool swig_owns_self_;
};

class NewtonWorld {
public:
  NewtonWorld();
  ~NewtonWorld() {
    if (swig_owns_self_)
      NewtonWorld_delete(swig_self_);
  }
  void Update(float timestep);
  void SetSubSteps(int substeps);
  void SetIterations(int iterations);

  explicit NewtonWorld(SwigObj_NewtonWorld* swig_self, bool swig_owns_self = true) noexcept : swig_self_{swig_self}, swig_owns_self_{swig_owns_self} {}
  NewtonWorld(NewtonWorld const&) = delete;
  NewtonWorld& operator=(NewtonWorld const&) = delete;
  NewtonWorld(NewtonWorld&& obj) noexcept : swig_self_{obj.swig_self_}, swig_owns_self_{obj.swig_owns_self_} { obj.swig_owns_self_ = false; }
  NewtonWorld& operator=(NewtonWorld&& obj) noexcept {
    if (swig_owns_self_)
      NewtonWorld_delete(swig_self_);
    swig_self_ = obj.swig_self_;
    swig_owns_self_ = obj.swig_owns_self_;
    obj.swig_owns_self_ = false;
    return *this;
  }
  SwigObj_NewtonWorld* swig_self() const noexcept { return swig_self_; }
  SwigObj_NewtonWorld* swig_self_;
  bool swig_owns_self_;
};


inline SWIG_CException::SWIG_CException(SWIG_CException const & ex) : SWIG_CException{SWIG_CException_copy(ex.swig_self())} {}
inline int SWIG_CException::code() const { return SWIG_CException_code_get(swig_self()); }
inline char * SWIG_CException::msg() const { return SWIG_CException_msg_get(swig_self()); }
inline SWIG_CException * SWIG_CException::get_pending() {
  auto swig_cres = SWIG_CException_get_pending();
  return swig_cres ? new SWIG_CException(swig_cres, false) : nullptr;
}
inline void SWIG_CException::reset_pending() { SWIG_CException_reset_pending(); }

#ifndef SWIG_swig_check_DEFINED
#define SWIG_swig_check_DEFINED 1

inline void swig_check() {
  if (SWIG_CException* swig_ex = SWIG_CException::get_pending()) {
    SWIG_CException swig_ex_copy{*swig_ex};
    delete swig_ex;
    SWIG_CException::reset_pending();
    throw swig_ex_copy;
  }
}

template <typename T> T swig_check(T x) {
  swig_check();
  return x;
}

#endif // SWIG_swig_check_DEFINED

inline NewtonWorld::NewtonWorld() : NewtonWorld{swig_check(NewtonWorld_new())} {}
inline void NewtonWorld::Update(float timestep) { NewtonWorld_Update(swig_self(), timestep); swig_check(); }
inline void NewtonWorld::SetSubSteps(int substeps) { NewtonWorld_SetSubSteps(swig_self(), substeps); swig_check(); }
inline void NewtonWorld::SetIterations(int iterations) { NewtonWorld_SetIterations(swig_self(), iterations); swig_check(); }

}

#endif /* __cplusplus */

#endif /* SWIG_newton_WRAP_H_ */
