all:
	make os=linux project=minizip -C dom
	make os=linux project=dom -C dom
	make os=linux project=fx -C fx
	make os=linux project=rt -C rt
	make os=linux project=viewer -C viewer
	
clean:
	make os=linux project=minizip -C dom clean
	make os=linux project=dom -C dom clean
	make os=linux project=fx -C fx clean
	make os=linux project=rt -C rt clean
	make os=linux project=viewer -C viewer clean
